from . import s_res_config_setting
from . import s_base_inegrate_shopee
from . import s_stock_warehouse
from . import s_product_template
from . import s_product_product
from . import s_sale_order
from . import s_stock_picking
from . import s_shopee_delivery_method
from . import s_ir_config_parameter
from . import s_res_partner
from . import s_stock_quant
from . import s_stock_move
