-- After running this SQL, please install Vietnamese Chart of Account (l10n_vn)
-- Then select VN - Chart of Accounts as company chart template (Settings>Invoice)
DELETE FROM stock_move;
DELETE FROM stock_move_line;
DELETE FROM stock_picking;
DELETE FROM stock_scrap;
DELETE FROM sale_order;
UPDATE pos_config SET journal_id = NULL, warehouse_id = 3, picking_type_id = 21;
DELETE FROM stock_rule WHERE picking_type_id IN (SELECT id FROM stock_picking_type WHERE company_id > 1 OR warehouse_id = 1);
DELETE FROM stock_picking_type WHERE company_id > 1 OR warehouse_id = 1;
DELETE FROM stock_warehouse WHERE company_id > 1 OR id = 1;
DELETE FROM res_company WHERE id > 1;
DELETE FROM account_partial_reconcile;
DELETE FROM account_payment_register;
DELETE FROM account_account_tag WHERE name LIKE 'Demo%' OR name = 'Office Furniture';
DELETE FROM account_payment_term WHERE name LIKE '30\% Advance%';
DELETE FROM account_move;
DELETE FROM pos_payment;
DELETE FROM pos_order;
DELETE FROM pos_session;
DELETE FROM pos_config;
DELETE FROM loyalty_program;
DELETE FROM pos_category;
DELETE FROM stock_quant;
DELETE FROM stock_production_lot;
DELETE FROM stock_valuation_layer;
DELETE FROM sale_order_template;
DELETE FROM product_template WHERE detailed_type NOT IN ('service','gift');
DELETE FROM delivery_carrier;
DELETE FROM channel_product_mappings;
DELETE FROM channel_template_mappings;
DELETE FROM product_pricelist_item;
DELETE FROM s_import_coupon_coupon;
DELETE FROM coupon_program;
DELETE FROM order_line_data_report;
DELETE FROM channel_attribute_mappings;
DELETE FROM channel_attribute_value_mappings;
DELETE FROM product_attribute;
DELETE FROM channel_order_mappings;
DELETE FROM channel_category_mappings;
DELETE FROM channel_pick_mappings;
DELETE FROM bravo_stock_picking_mappings;
DELETE FROM stock_rule;
DELETE FROM product_pricelist WHERE name <> 'Public Pricelist';
DELETE FROM mail_activity;
DELETE FROM res_users WHERE partner_id >= 7 AND partner_id < 45;
DELETE FROM res_partner WHERE id >= 7 AND id < 45;
DELETE FROM mail_message;
DELETE FROM mail_notification;
DELETE FROM sms_template WHERE name = 'Customer: automated SMS';
DELETE FROM product_attribute;
DELETE FROM product_attribute_value;
DELETE FROM s_product_brand;
DELETE FROM dong_hang;
DELETE FROM s_product_material;
DELETE FROM s_product_season;
DELETE FROM s_product_species;
DELETE FROM s_product_collection;
DELETE FROM s_product_color;
DELETE FROM s_product_size;
DELETE FROM s_product_gender;
DELETE FROM s_stock_picking_package;
DELETE FROM s_history_green_points;
DELETE FROM coupon_program;
DELETE FROM crm_tag;
DELETE FROM crm_team WHERE name='Pre-Sales';
DELETE FROM hr_employee;
DELETE FROM hr_job;
DELETE FROM hr_work_location;
DELETE FROM hr_employee_category;
DELETE FROM res_bank WHERE active = TRUE;
DELETE FROM res_partner_category;
UPDATE pos_payment_method SET journal_id = NULL;
DELETE FROM account_bank_statement;
DELETE FROM account_tax;
DELETE FROM s_internal_transfer;
DELETE FROM s_internal_transfer_line;
UPDATE ir_module_module SET demo = FALSE;
UPDATE res_currency SET active = TRUE WHERE name = 'VND';
UPDATE res_company SET currency_id = (SELECT id FROM res_currency WHERE name = 'VND');
