from . import rfm_segment
from . import rfm_score
from . import res_partner
from . import team_customer_segment
from . import res_config_settings
from . import sale_order
from . import mailing_mailing
from . import crm_lead
from . import rfm_segment_configuration
from . import rfm_partner_history
from . import crm_team
from . import ir_module_module
