from . import mail_channel
from . import sale_order
from . import res_config_setting
from . import helpdesk_team
from . import helpdesk_ticket
from . import res_partner
from . import helpdesk_stage
from . import s_mail_channel_queue
from . import s_helpdesk_ticket_queue
from . import s_mail_message
