# -*- coding: utf-8 -*-
from . import gift_card
from . import s_product_species
from . import s_product_size
from . import s_product_gender
from . import s_product_season
from . import s_product_color
from . import s_product_collection
from . import s_product_brand
from . import dong_hang
from . import res_partner
from . import pos_config
from . import coupon_coupon
from . import s_customer_rank
from . import product_template
from . import coupon_program
from . import pos_order
from . import pos_order_line
from . import s_order_history_points
from . import s_history_green_points
from . import s_product_product
from . import s_product_coupon_program
from . import s_res_config_settings
from . import s_import_coupon_coupon
from . import loyalty_program
from . import loyalty_rule
from . import product_pricelist
from . import s_pos_payment
from . import s_product_template_attribute_value
from . import s_lost_bill
from . import s_lost_bill_pos_order_line
from . import product_template_attribute_line_inherit
from . import product_pricelist_item
from . import s_pos_payment_method
from . import s_ir_logging
from . import s_history_loyalty_point_so
from . import s_sale_order
from . import s_mail_thread
from . import coupon_rule
