from . import product_template
from . import res_company
from . import res_config_settings
from . import stock_location
from . import stock_move
from . import stock_quant
from . import base_integrate_bravo
from . import product_attribute
from . import product_category
from . import product_product
from . import pos_order
from . import stock_picking
from . import bravo_mappings
from . import s_product_attribute_value
from . import s_res_partner
from . import sale_order
from . import s_import_bravo_id
from . import stock_warehouse
from . import s_product_brand_bravo_mapping
from . import ir_logging_inherit
from . import s_transit_stock_quant

