from . import s_loyalty_program
from . import s_loyalty_rule
from . import s_rule_point
from . import s_res_partner
from . import s_loyalty_reward
from . import s_pos_order
from . import s_res_config_setting
from . import s_reset_res_partner_rank
from . import s_sms_sms
from . import s_res_partner_otp
from . import s_product_product
from . import s_sale_order
from . import s_customer_rank
from . import s_pos_order_line
from . import s_sale_order_line
from . import s_lost_bill_pos_order_line
