# -*- coding: utf-8 -*-

from . import s_sync_product_magento
from . import res_config_settings
from . import res_partner
from . import channel_order_mappings
from . import channel_pick_mappings
from . import channel_pos_mappings
from . import pos_order
from . import product_attribute_value
from . import product_template
from . import product_product
from . import sale_order_line
from . import stock_picking
from . import s_channel_inventory_mappings
from . import s_stock_warehouse
from . import multi_channel_sale
from . import magento_web_stock
from . import stock_quant
from . import sale_order
from . import account_move_inherit
from . import s_history_green_points
from . import s_order_history_points
from . import s_product_attribute
from . import product_category
from . import channel_attribute_value_mappings_inherit
from . import account_move_line_inherit
from . import s_customer_loyalty_points
from . import stock_move
from . import s_magento_order_queue
